language: go

os:
  - linux
  - osx

env:
  - BADGE=linux
  - BADGE=osx
 
#hack to get some OS-specific badges
matrix:
 exclude:
  - os: linux
    env: BADGE=osx
  - os: osx
    env: BADGE=linux

go:
  - 1.13.x
  - 1.14.x
 
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - make
#  - go test ./test -v -covermode=count -coverprofile=coverage.out
  - go test $(go list ./src/...|grep -v ./src/asm*) -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken=$COVERALLS_TOKEN
