language: go

os:
  - linux
  - osx

go:
  - 1.13.x
 
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - make
#  - go test ./test -v -covermode=count -coverprofile=coverage.out
  - go test $(go list ./src/...|grep -v ./src/asm*) -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken=$COVERALLS_TOKEN
