version: "{build}"

#os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\JINGCW\gdp

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get -d ./...

build_script:
  - for /F "usebackq delims=" %aa in (`go list ./src/...^|findstr /v ./src/asm*`) do go test -v -cpu=2 %aa
  - for /F "usebackq  delims=" %aa in (`go list ./src/...^|findstr /v ./src/asm*`) do go test -v -cpu=1,2,4 -short -race %aa
